--오라클 딕셔너리 조회

drop table mig_tbl_list;
-- 배치작업용 조회쿼리(mysql 테이블생성 , bulk insert 구문)
create table mig_tbl_list AS

/* 테이블 생성 구문 만들기 */
SELECT
    OBJ.OWNER
  , TBL.TABLE_NAME
  , COL.SUM_DATA_LENGTH_BYTES
  , TBL.NUM_ROWS
  -- 1) 오라클 조회용 COUNT 쿼리
  , 'SELECT COUNT(*) FROM ' || TBL.OWNER || '.' || TBL.TABLE_NAME AS COUNT_TABLE_TEXT_ORACLE
   -- 2) MySQL CREATE TABLE DDL (CLOB 안전)
  , 'CREATE TABLE test.' || LOWER(TBL.TABLE_NAME) || '(' || CHR(10)     || COL.CREAT_COL_TEXT_MYSQL     || CHR(10) || ') ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;' AS CREAT_TABLE_TEXT_MYSQL
  -- 3) PostgreSQL CREATE TABLE DDL (CLOB 안전)
  , 'CREATE TABLE test.' || LOWER(TBL.TABLE_NAME) || '(' || CHR(10)     || COL.CREAT_COL_TEXT_POSTGRESQL     || CHR(10) || ');' AS CREAT_TABLE_TEXT_POSTGRESQL
  -- 4) MySQL Bulk Insert용 바인드 쿼리
  ,'INSERT INTO TEST.'||TBL.TABLE_NAME ||' VALUES ('||CREAT_INSERT_TEXT_MYSQL||')' CREAT_BIND_INSERT_TEXT_MYSQL
  ,'INSERT INTO TEST.'||TBL.TABLE_NAME ||' VALUES ('||CREAT_INSERT_TEXT_POSTGRESQL||')' CREAT_BIND_INSERT_TEXT_POSTGRE
  , 'Y' AS TARGET_YN
  , 0 AS FAIL
FROM DBA_OBJECTS OBJ
INNER JOIN DBA_TABLES TBL
    ON (OBJ.OWNER = TBL.OWNER AND OBJ.OBJECT_NAME = TBL.TABLE_NAME)
INNER JOIN (
    SELECT
        OWNER
      , TABLE_NAME
      , SUM(DATA_LENGTH_BYTES) AS SUM_DATA_LENGTH_BYTES

      -- [MySQL DDL] XMLAGG를 통한 CLOB 변환 (문자열 길이 제한 없음)
      , XMLAGG( XMLELEMENT(A, CASE WHEN COLUMN_ID = 1 THEN '  ' ELSE ', ' END
                || RPAD(LOWER(COLUMN_NAME), 30, ' ') || RPAD(DATA_TYPE_MYSQL, 20, ' ') || DATA_CONSTRAINT_NULLABLE, CHR(10)
            ) ORDER BY COLUMN_ID
        ).EXTRACT('//text()').GETCLOBVAL() AS CREAT_COL_TEXT_MYSQL

      -- [PostgreSQL DDL] XMLAGG를 통한 CLOB 변환
      , XMLAGG(
            XMLELEMENT(A, CASE WHEN COLUMN_ID = 1 THEN '  ' ELSE ', ' END
                || RPAD(LOWER(COLUMN_NAME), 30, ' ') || RPAD(DATA_TYPE_POSTGRESQL, 20, ' ') || DATA_CONSTRAINT_NULLABLE, CHR(10)
            ) ORDER BY COLUMN_ID
        ).EXTRACT('//text()').GETCLOBVAL() AS CREAT_COL_TEXT_POSTGRESQL

      -- [MySQL 바인드 ?] XMLAGG 적용
       ,LISTAGG( '%s' ,',' ) WITHIN GROUP(ORDER BY COLUMN_ID )    CREAT_INSERT_TEXT_MYSQL
       ,LISTAGG( '%s' ,',' ) WITHIN GROUP(ORDER BY COLUMN_ID )    CREAT_INSERT_TEXT_POSTGRESQL

    FROM (
        SELECT
            COL.OWNER
          , COL.TABLE_NAME
          , COL.COLUMN_NAME
          , COL.COLUMN_ID
          , DECODE(COL.NULLABLE, 'Y', 'NULL', 'N', 'NOT NULL') AS DATA_CONSTRAINT_NULLABLE

          -- 예상 메모리 크기 계산
          , CASE
                WHEN COL.DATA_TYPE IN ('VARCHAR2', 'CHAR', 'NVARCHAR2') THEN COL.DATA_LENGTH * 4
                WHEN COL.DATA_TYPE = 'NUMBER' THEN 22
                ELSE 8
            END AS DATA_LENGTH_BYTES

          -- [MySQL 데이터 타입 매핑 개선]
          , CASE
                WHEN COL.DATA_TYPE IN ('VARCHAR2', 'NVARCHAR2') THEN 'VARCHAR(' || COL.DATA_LENGTH || ')'
                WHEN COL.DATA_TYPE = 'CHAR' THEN 'CHAR(' || COL.DATA_LENGTH || ')'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE = 0 AND NVL(COL.DATA_PRECISION, 38) <= 9 THEN 'INT'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE = 0 AND COL.DATA_PRECISION > 9 THEN 'BIGINT'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE > 0 THEN 'DECIMAL(' || NVL(COL.DATA_PRECISION, 38) || ',' || COL.DATA_SCALE || ')'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE IS NULL THEN 'DOUBLE'
                WHEN COL.DATA_TYPE IN ('DATE', 'TIMESTAMP') THEN 'DATETIME'
                WHEN COL.DATA_TYPE IN ('CLOB', 'NCLOB') THEN 'LONGTEXT' -- [핵심 수정] 기존 LONGBLOB -> LONGTEXT
                WHEN COL.DATA_TYPE = 'BLOB' THEN 'LONGBLOB'
                ELSE 'TEXT'
            END AS DATA_TYPE_MYSQL

          -- [PostgreSQL 데이터 타입 매핑 개선]
          , CASE
                WHEN COL.DATA_TYPE IN ('VARCHAR2', 'NVARCHAR2') THEN 'VARCHAR(' || COL.DATA_LENGTH || ')'
                WHEN COL.DATA_TYPE = 'CHAR' THEN 'CHAR(' || COL.DATA_LENGTH || ')'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE = 0 AND NVL(COL.DATA_PRECISION, 38) <= 9 THEN 'INTEGER'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE = 0 AND COL.DATA_PRECISION > 9 THEN 'BIGINT'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE > 0 THEN 'NUMERIC(' || NVL(COL.DATA_PRECISION, 38) || ',' || COL.DATA_SCALE || ')'
                WHEN COL.DATA_TYPE = 'NUMBER' AND COL.DATA_SCALE IS NULL THEN 'DOUBLE PRECISION'
                WHEN COL.DATA_TYPE IN ('DATE', 'TIMESTAMP') THEN 'TIMESTAMP'
                WHEN COL.DATA_TYPE IN ('CLOB', 'NCLOB') THEN 'TEXT'
                WHEN COL.DATA_TYPE = 'BLOB' THEN 'BYTEA'
                ELSE 'TEXT'
            END AS DATA_TYPE_POSTGRESQL

        FROM DBA_TAB_COLUMNS COL
    )
    GROUP BY OWNER, TABLE_NAME
) COL ON (TBL.OWNER = COL.OWNER AND TBL.TABLE_NAME = COL.TABLE_NAME)
WHERE OBJ.OWNER = 'EDUORACLE'
  AND OBJ.OBJECT_TYPE = 'TABLE'
  AND NOT (OBJ.OBJECT_NAME LIKE '%$%' OR OBJ.OBJECT_NAME LIKE '%#%')
  AND COL.SUM_DATA_LENGTH_BYTES < 65535
ORDER BY TBL.NUM_ROWS ASC;



-- 작업실패 조회용 로그테이블
DROP TABLE eduoracle.mig_tbl_failed PURGE;
create table eduoracle.mig_tbl_failed
(
table_name varchar2(50)
,failed_desc clob
,exception_desc clob
,creat_dt date default sysdate
)
